---
# handlers file for assignment

- name: restart nginx
  service:
    name: nginx
    state: reloaded
- name: start nginx
  service:
    name: nginx
    state: started

- name: install nginx
  yum:
    name: nginx
    state: present


