---
- name: "NGINX test result"
  yum: 
    name: nginx
    state: present
  notify: restart nginx

- name: "Updating NGINX Config File Changes"
  template:
    dest: /etc/nginx/nginx.conf
    src: nginx.conf
    owner: ansible
    group: ansible
    mode: 0644
  notify: restart nginx

- name: "NGINX Config File Changes"
  template:
    dest: /etc/nginx/conf.d/site1.example.com.conf
    src: site1.example.com.conf
    owner: ansible
    group: ansible
    mode: 0644
  notify: restart nginx

- name: "NGINX Config File Changes"
  template:
    dest: /usr/share/nginx/site1.example.com
    src: site1_index.html
    owner: root
    group: root
    mode: 0644
  notify: restart nginx