---
- name: "Check if NGINX is installed"
  service_facts:

- debug:
    msg: nginx installed!
  when: "'nginx' in services"

- name: "NGINX test result"
  yum: 
    name: nginx
    state: present
  notify: restart nginx
  when: "'nginx' not in service_facts.services"

- name: "Updating NGINX Config File Changes"
  template:
    dest: /etc/nginx/nginx.conf
    src: nginx.conf
    owner: ansible
    group: ansible
    mode: 0644
  notify: restart nginx

- name: "NGINX Config File Changes"
  template:
    dest: /etc/nginx/conf.d/site1.example.com.conf
    src: site1.example.com.conf
    owner: ansible
    group: ansible
    mode: 0644
  notify: restart nginx

