---
- name: "Nginx test result"
  yum: 
    name: nginx
    state: present
  notify: restart nginx

- name: "Updating nginx config file changes"
  template:
    dest: /etc/nginx/nginx.conf
    src: nginx.conf
    owner: ansible
    group: ansible
    mode: 0644
  notify: restart nginx

- name: "Nginx config file changes"
  template:
    dest: /etc/nginx/conf.d/site1.example.com.conf
    src: site1.example.com.conf
    owner: ansible
    group: ansible
    mode: 0644
  notify: restart nginx

- name: "Nginx webpage changes"
  template:
    dest: /usr/share/nginx/site1.example.com/index.html
    src: site1_index.html
    owner: root
    group: root
    mode: 0644
  notify: restart nginx